tmkhogares/Models/Security/Accounts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Core.Models.Security
{
	public class Accounts
	{
		public Guid? Id { get; set; }
		public string UserName { get; set; }
		public string Password { get; set; }
		public string[] Roles { get; set; }
	}
}

tmkhogares/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Models.Security;


namespace ClaroGrandesSuperficies.Controllers
{
    public class AccountsController : Controller
    {
        // GET: Accounts
        public ActionResult Index()
        {
            if (SessionPersister.Id != null)
                return RedirectToAction("HomeAdmin","Home",null);

            return View();
        }






        [HttpPost]
        public ActionResult Login(AccountsViewModel avm)
        {

            AccountsModel am = new AccountsModel();
            Accounts ResultUser = am.Login(avm.Accounts.UserName, avm.Accounts.Password);
            if (string.IsNullOrEmpty(avm.Accounts.UserName) || string.IsNullOrEmpty(avm.Accounts.Password) || ResultUser == null)
            {
                ViewBag.Error = "Usuario o contraseña incorrectos";
                return View("index");
            }
            // get user data for the session.
            SessionPersister.UserName = avm.Accounts.UserName;
            SessionPersister.Id = ResultUser.Id;
            
           

            return RedirectToAction("index");

        }

        public ActionResult Logout()
        {
            SessionPersister.UserName = string.Empty;
            SessionPersister.Id = null;
            return View("index");
        }


        public ActionResult AccessDenied()
        {
            return View();
        }
    }
}

tmkhogares/Views/Accounts/AccessDenied.cshtml
@{
    ViewBag.Title = "Index";
}



<div class="container py-5">
    <div class="row">
        <div class="col-md-2 text-center">
            <p><i class="fa fa-exclamation fa-5x"></i><br />Status Code: 403</p>
        </div>
        <div class="col-md-10">
            <h3>OPPSSS!!!! Lo siento...</h3>
            <p>Lo siento,No tienes acceso a esta pagina  por razones de seguridad y de datos sensibles.<br />por favor regresa a la pagina anterior para que sigas Revisando.</p>
            <a class="btn btn-danger" href="javascript:history.back()">Regresar</a>
        </div>
    </div>
</div>

<div id="footer" class="text-center">
    &copy;Uno27 2018, Todos los derechos reservados.
</div>

tmkhogares/Views/Accounts/Index.cshtml
@{
    ViewBag.Title = "Index";

}
@model  Core.Models.Security.AccountsViewModel

<style>
    img.logo{
        /*box-shadow: 5px 5px 500px  #ff0000;*/
        margin-bottom: 20px;
        width: 300px;
    }
    /*.croseling{
        height: 60vh;
        width: 100vw;
    }*/
</style>
<div class="row">
    <div class="col-md-3">
        @*<img src="~/Content/images/uno27_claro.png"  class="logo croseling" />*@
    </div>
    <div class="col-xs-12 col-md-8">
        @*<img src="~/Content/images/logo2.png" class="logo" />*@
        <img src="~/Content/images/logo1.png" class="logo" />

    </div>
    <div class="col-md-3">
        @*<img src="~/Content/images/uno27_claro.png"  class="logo croseling" />*@
    </div>
    <div class="col-xs-12 col-md-7">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">Ingresar</h3>
            </div><!-- /.box-header -->
            <div class="box-body">

                @using (Html.BeginForm("Login", "Accounts", FormMethod.Post))
                {

                    <div class="form-group">
                        <br />
                        <label class="control-label col-md-2">Login</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Accounts.UserName, new { htmlAttributes = new { @class = "form-control", autofocus = "" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <br />
                        <br />

                        <label class="control-label col-md-2">contraseña</label>
                        <div class="col-md-10">
                            @Html.PasswordFor(model => model.Accounts.Password, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2"></label>
                        <div class="col-md-10">
                            <br />
                            <input type="submit" name="send" value="Ingresar" class="btn btn-success" />
                            @if (ViewBag.Error != null)
                            {
                                <div class="alert alert-danger">@ViewBag.Error</div>
                            }
                        </div>
                    </div>


                }
            </div>
        </div>

    </div>
</div>